# Generated by Django 3.0.7 on 2020-06-22 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OilPaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('author', models.CharField(max_length=150)),
                ('teacher', models.CharField(max_length=20)),
                ('series', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=500)),
                ('size', models.CharField(max_length=10)),
                ('type', models.CharField(max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='threeDmodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('author', models.CharField(max_length=150)),
                ('teacher', models.CharField(max_length=20)),
                ('series', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=500)),
                ('size', models.CharField(max_length=10)),
                ('type', models.CharField(max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('author', models.CharField(max_length=150)),
                ('teacher', models.CharField(max_length=20)),
                ('series', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=500)),
                ('size', models.CharField(max_length=10)),
                ('type', models.CharField(max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
