# Generated by Django 3.0.7 on 2020-06-22 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gallery_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DSTposter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('author', models.CharField(max_length=150)),
                ('teacher', models.CharField(max_length=20)),
                ('abstract', models.CharField(max_length=150)),
                ('criticalWords', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
