# Generated by Django 3.0.7 on 2020-06-24 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gallery_app', '0002_dstposter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=128)),
                ('phonenum', models.CharField(max_length=11)),
            ],
        ),
    ]
