# Generated by Django 3.0.7 on 2020-06-24 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gallery_app', '0003_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin',
            old_name='name',
            new_name='adminName',
        ),
    ]
