# Generated by Django 3.0.7 on 2020-06-24 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gallery_app', '0004_auto_20200624_1349'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin',
            old_name='adminName',
            new_name='name',
        ),
    ]
